drop table if exists member CASCADE;
create table member (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id) );

insert into member values('spring')

--by default as identity 구문으로 인해
--name value만 넣으면 id값은 자동으로 순서대로 매겨짐

-- jpql쿼리문 형식
-- select m from Member(객체) m(Ailas)
-- jpa 어노테이션으로 컨테이너에 있는 객체에 쿼리문을 날려서
-- 그걸 아래의 테이블을 향한 쿼리문으로 자동으로 바꿔줌
-- select * from Member(table)
